title: Pavan Kumar Pothula
description: Engineering Student
site_title: 'parker's portfolio'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: Pavan-Parker
blog_url: https://www.pavan-parker.github.io
email: pavankumar.reddy@iiitb.org
keybase_username: Pavan-Parker
twitter_username: Pavan-Parker
reddit_username: Pavan_Parker

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 